apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch-config
  namespace: rootcloud-mlaas
data:
  kubewatch.yaml: |
    namespace: ""
    handler:
      websocket:
        url: localhost:5000
      slack:
        token: <token>
        channel: <channel>
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
      secret: false
      configmap: false
