# 单pod运行
apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - image: piaobeizu2017/mlaas-kubewatch:v1.0
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
---
# job运行
apiVersion: batch/v1
kind: Job
metadata:
  name: kubewatch
  namespace: mlaas-v2
spec:
  template:
    metadata:
      name: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
      - image: piaobeizu2017/mlaas-kubewatch:v1.0
        imagePullPolicy: Always
        name: kubewatch
        volumeMounts:
        - name: kubewatch-config-volume
          mountPath: /root
      restartPolicy: OnFailure
      volumes:
      - name: kubewatch-config-volume
        configMap:
          name: kubewatch-config